CREATE DATABASE susdb;
USE susdb;

CREATE TABLE USUARIOS(
	cpf VARCHAR(11) NOT NULL PRIMARY KEY,
    senha VARCHAR(24) NOT NULL,
    nomeUsuario VARCHAR(200) NOT NULL,
    genero ENUM('M', 'F') NOT NULL,
    nascimento DATE NOT NULL,
    rg VARCHAR(10) NOT NULL,
    crm VARCHAR(11) NOT NULL DEFAULT '9999',
    telefone VARCHAR(11) NOT NULL,
    email VARCHAR(200) NOT NULL,
    tipo CHAR(3) NOT NULL,
    codEspecialidade INT NOT NULL DEFAULT 9999,
    codCidade varchar(3) NOT NULL
);


CREATE TABLE ESPECIALIDADE(
	codEspecialidade INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(200) NOT NULL
);

CREATE TABLE CONSULTAS(
	codConsultas INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	dataAtdm DATETIME,
    descricao TEXT,
    cpfUsuario VARCHAR(11) NOT NULL
);

CREATE TABLE ESTADOS(
	codEstado varchar(2) PRIMARY KEY NOT NULL,
    nomeEstado varchar(255) NOT NULL 
    
);

CREATE TABLE CIDADES(
	codCidade varchar(3) PRIMARY KEY NOT NULL,
    nomeCidade varchar(255) NOT NULL,
    codEstado varchar(2) NOT NULL
);

ALTER TABLE USUARIOS ADD 
FOREIGN KEY(codEspecialidade) REFERENCES ESPECIALIDADE(codEspecialidade);

ALTER TABLE CONSULTAS ADD 
FOREIGN KEY(cpfUsuario) REFERENCES USUARIOS(cpf);

ALTER TABLE CIDADES ADD 
FOREIGN KEY(codEstado) REFERENCES ESTADOS(codEstado);

ALTER TABLE USUARIOS ADD 
FOREIGN KEY(codCidade) REFERENCES CIDADES(codCidade);

INSERT INTO ESPECIALIDADE VALUES(
    9999,
    'Nao_sou_medico'
);

INSERT INTO ESTADOS VALUES(
    'BA',
    'BAHIA'
);

INSERT INTO CIDADES VALUES(
    'SSA',
    'SALVADOR',
    'BA'
);

SELECT * FROM cidades;


