CREATE DATABASE susdb;
USE susdb;

CREATE TABLE USUARIOS(
    cpf VARCHAR(11) NOT NULL PRIMARY KEY,
    senha VARCHAR(24) NOT NULL,
    nome VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL,
    tipo CHAR(3) NOT NULL
);

CREATE TABLE CONSULTAS(
	codConsultas INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	dataAtdm DATETIME,
    descricao TEXT,
    cpfUsuario VARCHAR(11) NOT NULL
);

ALTER TABLE CONSULTAS ADD 
FOREIGN KEY(cpfUsuario) REFERENCES USUARIOS(cpf);

SELECT * FROM usuarios;


